# Generated by Django 4.1.7 on 2023-03-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDApp', '0002_platformuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='gps_position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='gps_position_y',
            field=models.IntegerField(default=0),
        ),
    ]
