# Generated by Django 4.1.7 on 2023-05-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDApp', '0005_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('number_of_visits', models.IntegerField(default=0)),
            ],
        ),
    ]
