# Generated by Django 4.1.7 on 2023-05-08 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FDApp', '0006_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='viewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
